# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      environment:
        description: 'Deployment environment'
        required: false
        type: choice
        options:
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: 'https://isicas2026.wasmer.app/'

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
        BCMS_ORG_ID: ${{ secrets.BCMS_ORG_ID }}
        BCMS_INSTANCE_ID: ${{ secrets.BCMS_INSTANCE_ID }}
        BCMS_API_KEY_ID: ${{ secrets.BCMS_API_KEY_ID }}
        BCMS_API_KEY_SECRET: ${{ secrets.BCMS_API_KEY_SECRET }}
        PUBLIC_BCMS_ORG_ID: 68e3c74bea1914cdebd7fb15
        PUBLIC_BCMS_INSTANCE_ID: 68f0c0196bb9a9ccb70dddac
        PUBLIC_BCMS_API_KEY_ID: 68f0c0206bb9a9ccb70dddcd
        PUBLIC_BCMS_API_KEY_SECRET: 85a30f8e27c1a28108a6c23fdfe10fe82cdf7006c25635817330daa76c49421a
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://isicas2026.wasmer.app/'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v5
      with:
        name: node-app

    - name: Setup Wasmer
      uses: wasmerio/setup-wasmer@v3.1

    - name: Deploy to Wasmer Edge
      run: wasmer deploy
      env:
        WASMER_TOKEN: ${{ secrets.WASMER_TOKEN }}
